name: Build and Deploy

on:
  - push
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Batleforce*3
          POSTGRES_DB: nome_database
        ports:
          - 5432:5432

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v2

      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13.2"

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Configurar DATABASE_URL corretamente
        run: echo "DATABASE_URL=postgresql://postgres:Batleforce*3@postgres:5432/nome_database" >> $GITHUB_ENV

      - name: Esperando o PostgreSQL ficar pronto
        run: |
          echo "⏳ Aguardando o banco de dados iniciar (espera inicial de 10s)..."
          sleep 10
          for i in {1..20}; do
            echo "Tentativa $i: Verificando conexão com o banco..."
            if PGPASSWORD=Batleforce*3 psql -h postgres -U postgres -d nome_database -c "SELECT 1" > /dev/null 2>&1; then
              echo "✅ Banco de dados está pronto!"
              break
            fi
            echo "⏳ Aguardando mais 5 segundos..."
            sleep 5
          done

      - name: Executar pytest
        run: pytest teste.py
