name: Build and Deploy

on:
  - push
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: nome_database
        ports:
          - 5432:5432

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v2

      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r BackEnd/requirements.txt

      - name: Instalar psycopg2-binary
        run: pip install psycopg2-binary

      - name: Esperando o PostgreSQL ficar pronto
        run: |
          for i in {1..10}; do
            if pg_isready -h localhost -p 5432; then
              echo "Banco de dados está pronto!"
              break
            fi
            echo "Esperando o banco de dados iniciar..."
            sleep 3
          done

      - name: Executar pytest
        env:
          DATABASE_URL: postgresql://postgres:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/nome_database
        run: pytest BackEnd/teste.py
