name: Build and Deploy

on:
  - push
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin -d mydatabase"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2

      - name: Instalando o Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.2"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r BackEnd/requirements.txt

      - name: Executar pytest
        env:
          DATABASE_URL: postgresql://admin:admin@localhost:5432/mydatabase
        run: pytest BackEnd/teste.py
