name: Build and Deploy

on:
  - push
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: mydatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U admin -d mydatabase"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v2

      - name: Instalar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.2"

      - name: Atualizar pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r BackEnd/requirements.txt

      - name: Instalar psycopg2-binary
        run: pip install psycopg2-binary

      - name: Configurar variável DATABASE_URL
        run: echo "DATABASE_URL=postgresql://admin:admin@postgres:5432/mydatabase" >> $GITHUB_ENV

      - name: Esperando o PostgreSQL ficar pronto
        run: |
          echo "⏳ Aguardando o banco de dados iniciar (espera inicial de 10s)..."
          sleep 10
          for i in {1..30}; do
            echo "Tentativa $i: Verificando conexão com o banco..."
            if PGPASSWORD=admin psql -h postgres -U admin -d mydatabase -c "SELECT 1" > /dev/null 2>&1; then
              echo "✅ Banco de dados está pronto!"
              break
            fi
            echo "⏳ Aguardando mais 5 segundos..."
            sleep 5
          done

      - name: Executar pytest
        working-directory: BackEnd
        run: pytest teste.py
